version: '3.2'
services:

  web:
    restart: always
    build: ./enrolment-ui/
    env_file: .env
    volumes: 
      - web-data:/data/web
    depends_on:
      - api

  api:
    restart: always
    build: ./enrolment-service/
    expose:
      - "8000"
    volumes: 
      - api-data:/data/api
      - ./presisted_data/logs/django:/var/log/gunicorn
    env_file: .env
    entrypoint: /entrypoint.sh 
    depends_on:
      - postgres

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:8080"
      - "443:8080"
      - "8000:8000"
    volumes: 
      - type: volume
        source: web-data
        target: /data/web
        read_only: true
      - type: volume
        source: api-data
        target: /data/api
        read_only: true
      - ./presisted_data/logs/nginx:/var/log/nginx
    depends_on:
      - web
      - api

  postgres:
    restart: always
    image: postgres:10.1
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./presisted_data/postgresql:/var/lib/postgresql/data
    env_file: .env
    expose:
      - "5432"

volumes:
  web-data:
  api-data: